vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|20 Feb 2001 08:54:08 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|20 Feb 2001 08:54:08 -0000
vti_filesize:IR|648
vti_cachedlinkinfo:VX|A|order.asp
vti_cachedsvcrellinks:VX|FAUS|100asp/08/order.asp
vti_cachedtitle:SR|订购水果
vti_title:SR|订购水果
vti_cachedbodystyle:SR|<BODY>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
