vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|30 Apr 2001 15:52:08 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|30 Apr 2001 15:52:08 -0000
vti_filesize:IR|1010
vti_cachedlinkinfo:VX|
vti_cachedsvcrellinks:VX|
vti_cachedtitle:SR|用Tools组件生成随机整数
vti_title:SR|用Tools组件生成随机整数
vti_cachedbodystyle:SR|<BODY BGCOLOR="White" topmargin="10" leftmargin="10">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_backlinkinfo:VX|
