vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|02 Apr 2001 06:36:16 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|02 Apr 2001 06:36:16 -0000
vti_filesize:IR|553
vti_cachedlinkinfo:VX|H|AdRot.asp
vti_cachedsvcrellinks:VX|FHUS|100asp/46/AdRot.asp
vti_cachedtitle:SR|动态广告条
vti_title:SR|动态广告条
vti_cachedbodystyle:SR|<BODY BGCOLOR="White" TOPMARGIN="10" LEFTMARGIN="10">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
