vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|26 Mar 2001 13:34:46 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|26 Mar 2001 13:34:46 -0000
vti_filesize:IR|4371
vti_cachedlinkinfo:VX|D|index.asp S|bg.gif H|index.asp H|javascript:confirmDel(<%=\\ rs("id")\\ %>) A|index.asp A|index.asp
vti_cachedsvcrellinks:VX|FDUS|100asp/81/index.asp FSUS|100asp/81/bg.gif FHUS|100asp/81/index.asp SHUS|javascript:confirmDel(<%=\\ rs("id")\\ %>) FAUS|100asp/81/index.asp FAUS|100asp/81/index.asp
vti_cachedtitle:SR|实例　通讯簿
vti_title:SR|实例　通讯簿
vti_cachedbodystyle:SR|<body background="bg.gif">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
