vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|28 Mar 2001 04:07:00 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|28 Mar 2001 04:07:00 -0000
vti_filesize:IR|1653
vti_cachedlinkinfo:VX|H|javascript:history.back() H|javascript:history.bakc() H|javascript:history.back() H|javascript:history.back() H|http://fang/bbs/
vti_cachedsvcrellinks:VX|SHUS|javascript:history.back() SHUS|javascript:history.bakc() SHUS|javascript:history.back() SHUS|javascript:history.back() NHHS|http://fang/bbs/
vti_cachedbodystyle:SR|<body bgcolor=#c1f7d8>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
