vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|28 Mar 2001 04:32:10 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|28 Mar 2001 04:32:10 -0000
vti_filesize:IR|2489
vti_cachedlinkinfo:VX|H|readarticle.asp H|newmessage.asp
vti_cachedsvcrellinks:VX|NHUS|100asp/94/readarticle.asp NHUS|100asp/94/newmessage.asp
vti_cachedtitle:SR|浏览标题
vti_title:SR|浏览标题
vti_cachedbodystyle:SR|<body bgcolor=#c1f7d8>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_backlinkinfo:VX|
