vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|28 Mar 2001 14:21:36 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|28 Mar 2001 14:21:36 -0000
vti_filesize:IR|1732
vti_cachedlinkinfo:VX|S|picture/close.bmp S|picture/text.bmp
vti_cachedsvcrellinks:VX|NSUS|100asp/78/picture/close.bmp NSUS|100asp/78/picture/text.bmp
vti_cachedtitle:SR|实例 多层目录显示
vti_title:SR|实例 多层目录显示
vti_cachedbodystyle:SR|<body>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
