vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|27 Mar 2001 08:44:22 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|27 Mar 2001 08:44:22 -0000
vti_filesize:IR|1118
vti_cachedlinkinfo:VX|S|bar.gif S|bar.gif S|bar.gif
vti_cachedsvcrellinks:VX|FSUS|100asp/76/bar.gif FSUS|100asp/76/bar.gif FSUS|100asp/76/bar.gif
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
