vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|11 Apr 2001 21:19:04 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|11 Apr 2001 21:19:04 -0000
vti_filesize:IR|1320
vti_cachedlinkinfo:VX|D|register.asp A|checklogin.asp
vti_cachedsvcrellinks:VX|FDUS|100asp/90/register.asp FAUS|100asp/90/checklogin.asp
vti_cachedtitle:SR|聊天室
vti_title:SR|聊天室
vti_cachedbodystyle:SR|<body bgcolor=lightgreen>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
