vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|08 Apr 2001 18:39:34 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|08 Apr 2001 18:39:34 -0000
vti_filesize:IR|613
vti_cachedlinkinfo:VX|F|Content.asp F|message.asp F|send.asp
vti_cachedsvcrellinks:VX|FFUS|100asp/90/Content.asp FFUS|100asp/90/message.asp FFUS|100asp/90/send.asp
vti_cachedtitle:SR|聊天室
vti_title:SR|聊天室
vti_cachedbodystyle:SR|<body>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|GENERATOR Microsoft\\ Visual\\ Studio\\ 6.0
vti_generator:SR|Microsoft Visual Studio 6.0
vti_hasframeset:BR|true
