vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|31 Mar 2001 15:30:48 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|31 Mar 2001 15:30:48 -0000
vti_filesize:IR|1128
vti_cachedlinkinfo:VX|A|adduser.asp
vti_cachedsvcrellinks:VX|FAUS|100asp/90/adduser.asp
vti_cachedtitle:SR|聊天室
vti_title:SR|聊天室
vti_cachedbodystyle:SR|<body bgcolor=lightgreen>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
