vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|30 Apr 2001 15:40:56 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|30 Apr 2001 15:40:56 -0000
vti_filesize:IR|2625
vti_cachedlinkinfo:VX|A|index.asp
vti_cachedsvcrellinks:VX|FAUS|100asp/20/index.asp
vti_cachedtitle:SR|石头、剪子、布小游戏
vti_title:SR|石头、剪子、布小游戏
vti_cachedbodystyle:SR|<body>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
