vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|06 May 2001 11:59:28 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|06 May 2001 11:59:28 -0000
vti_filesize:IR|284
vti_cachedlinkinfo:VX|
vti_cachedsvcrellinks:VX|
vti_cachedtitle:SR|生成一个Guid
vti_title:SR|生成一个Guid
vti_cachedbodystyle:SR|<BODY>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|GENERATOR Microsoft\\ Visual\\ Studio\\ 6.0
vti_generator:SR|Microsoft Visual Studio 6.0
