vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|07 Apr 1999 13:15:08 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|07 Apr 1999 13:15:08 -0000
vti_filesize:IR|1383
vti_cachedlinkinfo:VX|A|viewcode.asp
vti_cachedsvcrellinks:VX|FAUS|100asp/33/viewcode.asp
vti_cachedtitle:SR|ASP源码浏览器
vti_title:SR|ASP源码浏览器
vti_cachedbodystyle:SR|<BODY BGCOLOR=#FFFFFF>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
