vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|29 Mar 2001 21:26:58 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|29 Mar 2001 21:26:58 -0000
vti_filesize:IR|949
vti_cachedlinkinfo:VX|
vti_cachedsvcrellinks:VX|
vti_cachedtitle:SR|查看购物蓝
vti_title:SR|查看购物蓝
vti_cachedbodystyle:SR|<BODY text=MediumSlateBlue>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|GENERATOR Microsoft\\ Visual\\ Studio\\ 6.0
vti_generator:SR|Microsoft Visual Studio 6.0
