vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|29 Mar 2001 21:28:48 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|29 Mar 2001 21:28:48 -0000
vti_filesize:IR|1173
vti_cachedlinkinfo:VX|H|display.asp H|clear.asp A|Add.asp
vti_cachedsvcrellinks:VX|FHUS|100asp/85/display.asp FHUS|100asp/85/clear.asp FAUS|100asp/85/Add.asp
vti_cachedtitle:SR|网上书店
vti_title:SR|网上书店
vti_cachedbodystyle:SR|<body bgcolor="#DFEFFF" text="#0000FF">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_backlinkinfo:VX|
