vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|05 Apr 2001 16:27:26 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|05 Apr 2001 16:27:26 -0000
vti_filesize:IR|1393
vti_cachedlinkinfo:VX|
vti_cachedsvcrellinks:VX|
vti_cachedtitle:SR|图书管理
vti_title:SR|图书管理
vti_cachedbodystyle:SR|<body bgcolor="#f0ffff">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
