vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|05 Apr 2001 16:31:50 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|05 Apr 2001 16:31:50 -0000
vti_filesize:IR|1631
vti_cachedlinkinfo:VX|A|index.asp A|add.asp A|del.asp A|lend.asp A|still.asp
vti_cachedsvcrellinks:VX|FAUS|100asp/88/index.asp FAUS|100asp/88/add.asp FAUS|100asp/88/del.asp FAUS|100asp/88/lend.asp FAUS|100asp/88/still.asp
vti_cachedtitle:SR|图书管理
vti_title:SR|图书管理
vti_cachedbodystyle:SR|<body bgcolor="#f0ffff" vlink=mediumslateblue>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
