vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|01 Apr 2001 12:42:06 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|01 Apr 2001 12:42:06 -0000
vti_filesize:IR|662
vti_cachedlinkinfo:VX|F|top.asp F|left.asp F|right.asp
vti_cachedsvcrellinks:VX|FFUS|100asp/87/top.asp FFUS|100asp/87/left.asp FFUS|100asp/87/right.asp
vti_cachedtitle:SR|人事管理
vti_title:SR|人事管理
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312
vti_hasframeset:BR|true
