vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|02 Apr 2001 08:13:08 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|02 Apr 2001 08:13:08 -0000
vti_filesize:IR|2306
vti_cachedlinkinfo:VX|D|del.asp A|add.asp H|javascript:confirmDel(<%=\\ rs("id")\\ %>)
vti_cachedsvcrellinks:VX|FDUS|100asp/87/del.asp FAUS|100asp/87/add.asp SHUS|javascript:confirmDel(<%=\\ rs("id")\\ %>)
vti_cachedbodystyle:SR|<BODY bgcolor=#99cccc>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|GENERATOR Microsoft\\ Visual\\ Studio\\ 6.0
vti_generator:SR|Microsoft Visual Studio 6.0
