vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|01 Apr 2001 16:13:56 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|01 Apr 2001 16:13:56 -0000
vti_filesize:IR|1200
vti_cachedlinkinfo:VX|H|manage.asp H|manage.asp
vti_cachedsvcrellinks:VX|FHUS|100asp/87/manage.asp FHUS|100asp/87/manage.asp
vti_cachedbodystyle:SR|<body  bgcolor=AntiqueWhite>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
