vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|01 Apr 2001 12:14:42 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|01 Apr 2001 12:14:42 -0000
vti_filesize:IR|349
vti_cachedlinkinfo:VX|
vti_cachedsvcrellinks:VX|
vti_cachedbodystyle:SR|<BODY>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|GENERATOR Microsoft\\ Visual\\ Studio\\ 6.0
vti_generator:SR|Microsoft Visual Studio 6.0
