vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|14 Oct 2002 06:46:32 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|14 Oct 2002 06:46:32 -0000
vti_filesize:IR|16975
vti_cachedlinkinfo:VX|H|boardhelp.asp A|login.asp H|reg.asp H|lostpass.asp H|<%=Request.ServerVariables("HTTP_REFERER")%> H|<%=Request.ServerVariables("HTTP_REFERER")%> H|<%=\\ Forum_info(3)\\ %> S|<%=\\ Forum_info(6)\\ %> D|clsid:D27CDB6E-AE6D-11cf-96B8-444553540000 D|http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab S|http://www.dvbbs.net/skin/default/dvbanner.swf K|CHAR.asp H|mailto:<%=Forum_info(5)%> H|boardhelp.asp H|login.asp S|<%=Forum_info(7)%>navspacer.gif H|reg.asp H|cookies.asp H|cookies.asp S|<%=Forum_info(7)%>navspacer.gif H|login.asp S|<%=Forum_info(7)%>navspacer.gif H|usermanager.asp S|<%=Forum_info(7)%>navspacer.gif H|query.asp S|<%=Forum_info(7)%>navspacer.gif H|boardstat.asp S|<%=Forum_info(7)%>navspacer.gif H|boardhelp.asp S|<%=Forum_info(7)%>navspacer.gif H|logout.asp S|<%=Forum_info(7)%>navspacer.gif H|dispuser.asp H|JavaScript:openScript('messanger.asp?action=new',500,400) H|topicwithme.asp H|topicwithme.asp H|dispuser.asp S|pic/mail.wav S|<%=Forum_info(7)%>msg_new_bar.gif H|usersms.asp H|javascript:openScript('messanger.asp?action=read&id=<%=inceptid(1)%>&sender=<%=inceptid(2)%>',500,400) S|<%=Forum_info(7)%>msg_no_new_bar.gif H|usersms.asp S|<%=Forum_info(7)%>Forum_nav.gif H|index.asp
vti_cachedsvcrellinks:VX|NHUS|dvbbs5/INC/boardhelp.asp NAUS|dvbbs5/INC/login.asp NHUS|dvbbs5/INC/reg.asp NHUS|dvbbs5/INC/lostpass.asp UHUS|<%=Request.ServerVariables("HTTP_REFERER")%> UHUS|<%=Request.ServerVariables("HTTP_REFERER")%> UHUS|<%=\\ Forum_info(3)\\ %> USUS|<%=\\ Forum_info(6)\\ %> NDUS|clsid:D27CDB6E-AE6D-11cf-96B8-444553540000 NDHS|http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab NSHS|http://www.dvbbs.net/skin/default/dvbanner.swf FKUS|dvbbs5/INC/CHAR.asp UHUS|mailto:<%=Forum_info(5)%> NHUS|dvbbs5/INC/boardhelp.asp NHUS|dvbbs5/INC/login.asp USUS|<%=Forum_info(7)%>navspacer.gif NHUS|dvbbs5/INC/reg.asp NHUS|dvbbs5/INC/cookies.asp NHUS|dvbbs5/INC/cookies.asp USUS|<%=Forum_info(7)%>navspacer.gif NHUS|dvbbs5/INC/login.asp USUS|<%=Forum_info(7)%>navspacer.gif NHUS|dvbbs5/INC/usermanager.asp USUS|<%=Forum_info(7)%>navspacer.gif NHUS|dvbbs5/INC/query.asp USUS|<%=Forum_info(7)%>navspacer.gif NHUS|dvbbs5/INC/boardstat.asp USUS|<%=Forum_info(7)%>navspacer.gif NHUS|dvbbs5/INC/boardhelp.asp USUS|<%=Forum_info(7)%>navspacer.gif NHUS|dvbbs5/INC/logout.asp USUS|<%=Forum_info(7)%>navspacer.gif NHUS|dvbbs5/INC/dispuser.asp SHUS|JavaScript:openScript('messanger.asp?action=new',500,400) NHUS|dvbbs5/INC/topicwithme.asp NHUS|dvbbs5/INC/topicwithme.asp NHUS|dvbbs5/INC/dispuser.asp NSUS|dvbbs5/INC/pic/mail.wav USUS|<%=Forum_info(7)%>msg_new_bar.gif NHUS|dvbbs5/INC/usersms.asp SHUS|javascript:openScript('messanger.asp?action=read&id=<%=inceptid(1)%>&sender=<%=inceptid(2)%>',500,400) USUS|<%=Forum_info(7)%>msg_no_new_bar.gif NHUS|dvbbs5/INC/usersms.asp USUS|<%=Forum_info(7)%>Forum_nav.gif NHUS|dvbbs5/INC/index.asp
vti_cachedtitle:SR|--
vti_title:SR|--
vti_cachedbodystyle:SR|<body <%=Forum_body(11)%>>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html; keywords 动网先锋,动网论坛,dvbbs
