vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|17 Apr 2001 20:37:10 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|17 Apr 2001 20:37:10 -0000
vti_filesize:IR|1288
vti_cachedlinkinfo:VX|
vti_cachedsvcrellinks:VX|
vti_cachedtitle:SR|数据库的结构显示
vti_title:SR|数据库的结构显示
vti_cachedbodystyle:SR|<body bgcolor=Peachpuff>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
