vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|29 Sep 2002 06:58:22 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|29 Sep 2002 06:58:22 -0000
vti_filesize:IR|19816
vti_cachedlinkinfo:VX|Q|forum_admin.css A|admin_pic.asp S|<%=Forum_info(7)%><%=Forum_pic(0)%> S|<%=Forum_info(7)%><%=Forum_pic(1)%> S|<%=Forum_info(7)%><%=Forum_pic(2)%> S|<%=Forum_info(7)%><%=Forum_pic(3)%> S|<%=Forum_info(7)%><%=Forum_pic(4)%> S|<%=Forum_info(7)%><%=Forum_pic(7)%> S|<%=Forum_info(7)%><%=Forum_pic(6)%> S|<%=Forum_info(7)%><%=Forum_pic(15)%> S|<%=Forum_info(7)%><%=Forum_pic(14)%> S|<%=Forum_info(7)%><%=Forum_boardpic(0)%> S|<%=Forum_info(7)%><%=Forum_boardpic(1)%> S|<%=Forum_info(7)%><%=Forum_boardpic(2)%> S|<%=Forum_info(7)%><%=Forum_boardpic(4)%> S|<%=Forum_info(7)%><%=Forum_boardpic(3)%> S|<%=Forum_info(7)%><%=Forum_boardpic(5)%> S|<%=Forum_info(7)%><%=Forum_boardpic(6)%> S|<%=Forum_info(7)%><%=Forum_boardpic(7)%> S|<%=Forum_info(7)%><%=Forum_boardpic(8)%> S|<%=Forum_info(7)%><%=Forum_boardpic(9)%> S|<%=Forum_info(7)%><%=Forum_boardpic(10)%> S|<%=Forum_info(7)%><%=Forum_boardpic(11)%> S|<%=Forum_info(7)%><%=Forum_boardpic(12)%> S|<%=Forum_info(7)%><%=Forum_boardpic(13)%> S|<%=Forum_info(7)%><%=Forum_boardpic(14)%> S|<%=Forum_info(7)%><%=Forum_boardpic(15)%> S|<%=Forum_info(7)%><%=Forum_boardpic(16)%> S|<%=Forum_info(7)%><%=Forum_statePic(0)%> S|<%=Forum_info(7)%><%=Forum_statePic(1)%> S|<%=Forum_info(7)%><%=Forum_statePic(2)%> S|<%=Forum_info(7)%><%=Forum_statePic(3)%> S|<%=Forum_info(7)%><%=Forum_statePic(4)%> S|<%=Forum_info(7)%><%=Forum_statePic(12)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(0)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(1)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(2)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(4)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(3)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(5)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(6)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(7)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(21)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(9)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(8)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(10)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(11)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(12)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(13)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(14)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(15)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(16)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(17)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(18)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(19)%> S|<%=Forum_info(7)%><%=Forum_TopicPic(20)%>
vti_cachedsvcrellinks:VX|FQUS|dvbbs5/forum_admin.css FAUS|dvbbs5/admin_pic.asp USUS|<%=Forum_info(7)%><%=Forum_pic(0)%> USUS|<%=Forum_info(7)%><%=Forum_pic(1)%> USUS|<%=Forum_info(7)%><%=Forum_pic(2)%> USUS|<%=Forum_info(7)%><%=Forum_pic(3)%> USUS|<%=Forum_info(7)%><%=Forum_pic(4)%> USUS|<%=Forum_info(7)%><%=Forum_pic(7)%> USUS|<%=Forum_info(7)%><%=Forum_pic(6)%> USUS|<%=Forum_info(7)%><%=Forum_pic(15)%> USUS|<%=Forum_info(7)%><%=Forum_pic(14)%> USUS|<%=Forum_info(7)%><%=Forum_boardpic(0)%> USUS|<%=Forum_info(7)%><%=Forum_boardpic(1)%> USUS|<%=Forum_info(7)%><%=Forum_boardpic(2)%> USUS|<%=Forum_info(7)%><%=Forum_boardpic(4)%> USUS|<%=Forum_info(7)%><%=Forum_boardpic(3)%> USUS|<%=Forum_info(7)%><%=Forum_boardpic(5)%> USUS|<%=Forum_info(7)%><%=Forum_boardpic(6)%> USUS|<%=Forum_info(7)%><%=Forum_boardpic(7)%> USUS|<%=Forum_info(7)%><%=Forum_boardpic(8)%> USUS|<%=Forum_info(7)%><%=Forum_boardpic(9)%> USUS|<%=Forum_info(7)%><%=Forum_boardpic(10)%> USUS|<%=Forum_info(7)%><%=Forum_boardpic(11)%> USUS|<%=Forum_info(7)%><%=Forum_boardpic(12)%> USUS|<%=Forum_info(7)%><%=Forum_boardpic(13)%> USUS|<%=Forum_info(7)%><%=Forum_boardpic(14)%> USUS|<%=Forum_info(7)%><%=Forum_boardpic(15)%> USUS|<%=Forum_info(7)%><%=Forum_boardpic(16)%> USUS|<%=Forum_info(7)%><%=Forum_statePic(0)%> USUS|<%=Forum_info(7)%><%=Forum_statePic(1)%> USUS|<%=Forum_info(7)%><%=Forum_statePic(2)%> USUS|<%=Forum_info(7)%><%=Forum_statePic(3)%> USUS|<%=Forum_info(7)%><%=Forum_statePic(4)%> USUS|<%=Forum_info(7)%><%=Forum_statePic(12)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(0)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(1)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(2)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(4)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(3)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(5)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(6)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(7)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(21)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(9)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(8)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(10)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(11)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(12)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(13)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(14)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(15)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(16)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(17)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(18)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(19)%> USUS|<%=Forum_info(7)%><%=Forum_TopicPic(20)%>
vti_cachedtitle:SR|--管理页面
vti_title:SR|--管理页面
vti_cachedbodystyle:SR|<BODY leftmargin="0" bottommargin="0" rightmargin="0" topmargin="0" marginheight="0" marginwidth="0" bgcolor="#DDEEFF">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|GENERATOR Microsoft\\ FrontPage\\ 3.0
vti_generator:SR|Microsoft FrontPage 3.0
