vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|11 Oct 2002 05:26:00 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|11 Oct 2002 05:26:00 -0000
vti_filesize:IR|6528
vti_cachedlinkinfo:VX|S|inc/ubbcode.js A|SaveAnnounce.asp H|reg.asp H|lostpass.asp S|face/face<%=i%>.gif S|face/face<%=i%>.gif H|javascript:money() H|javascript:point() H|javascript:usercp() H|javascript:power() H|javascript:article() H|javascript:replyview() S|saveannounce_upload.asp A|preview.asp
vti_cachedsvcrellinks:VX|FSUS|dvbbs5/inc/ubbcode.js FAUS|dvbbs5/SaveAnnounce.asp FHUS|dvbbs5/reg.asp FHUS|dvbbs5/lostpass.asp USUS|face/face<%=i%>.gif USUS|face/face<%=i%>.gif SHUS|javascript:money() SHUS|javascript:point() SHUS|javascript:usercp() SHUS|javascript:power() SHUS|javascript:article() SHUS|javascript:replyview() FSUS|dvbbs5/saveannounce_upload.asp FAUS|dvbbs5/preview.asp
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
