vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|15 Oct 2002 02:19:08 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|15 Oct 2002 02:19:08 -0000
vti_filesize:IR|31711
vti_cachedlinkinfo:VX|H|announce.asp S|<%=Forum_info(7)&Forum_boardpic(1)%> H|vote.asp S|<%=Forum_info(7)&Forum_boardpic(2)%> H|reannounce.asp S|<%=Forum_info(7)&Forum_boardpic(4)%> H|go.asp S|<%=Forum_info(7)&Forum_boardpic(14)%> H|javascript:this.location.reload() S|<%=Forum_info(7)&Forum_boardpic(15)%> H|dispbbs.asp S|<%=Forum_info(7)&skinpic%> H|go.asp S|<%=Forum_info(7)&Forum_boardpic(13)%> K|dispbbs.asp S|<%=Forum_info(7)&Forum_TopicPic(0)%> D|CLSID:8856F961-340A-11D0-A96B-00C04FD705A2 H|report.asp S|<%=Forum_info(7)&Forum_TopicPic(1)%> H|printpage.asp S|<%=Forum_info(7)&Forum_TopicPic(2)%> H|pag.asp S|<%=Forum_info(7)&Forum_TopicPic(3)%> H|favadd.asp S|<%=Forum_info(7)&Forum_TopicPic(4)%> H|sendpage.asp S|<%=Forum_info(7)&Forum_TopicPic(5)%> K|dispbbs.asp S|<%=Forum_info(7)&Forum_TopicPic(6)%> K|dispbbs.asp S|pic/gotop.gif A|SaveReAnnounce.asp H|reg.asp H|lostpass.asp H|admin_postings.asp H|admin_postings.asp H|admin_postings.asp H|admin_postings.asp H|admin_postings.asp H|admin_postings.asp H|admin_postings.asp H|announcements.asp A|preview.asp
vti_cachedsvcrellinks:VX|FHUS|dvbbs5/announce.asp USUS|<%=Forum_info(7)&Forum_boardpic(1)%> FHUS|dvbbs5/vote.asp USUS|<%=Forum_info(7)&Forum_boardpic(2)%> FHUS|dvbbs5/reannounce.asp USUS|<%=Forum_info(7)&Forum_boardpic(4)%> FHUS|dvbbs5/go.asp USUS|<%=Forum_info(7)&Forum_boardpic(14)%> SHUS|javascript:this.location.reload() USUS|<%=Forum_info(7)&Forum_boardpic(15)%> FHUS|dvbbs5/dispbbs.asp USUS|<%=Forum_info(7)&skinpic%> FHUS|dvbbs5/go.asp USUS|<%=Forum_info(7)&Forum_boardpic(13)%> FKUS|dvbbs5/dispbbs.asp USUS|<%=Forum_info(7)&Forum_TopicPic(0)%> NDUS|CLSID:8856F961-340A-11D0-A96B-00C04FD705A2 FHUS|dvbbs5/report.asp USUS|<%=Forum_info(7)&Forum_TopicPic(1)%> FHUS|dvbbs5/printpage.asp USUS|<%=Forum_info(7)&Forum_TopicPic(2)%> FHUS|dvbbs5/pag.asp USUS|<%=Forum_info(7)&Forum_TopicPic(3)%> FHUS|dvbbs5/favadd.asp USUS|<%=Forum_info(7)&Forum_TopicPic(4)%> FHUS|dvbbs5/sendpage.asp USUS|<%=Forum_info(7)&Forum_TopicPic(5)%> FKUS|dvbbs5/dispbbs.asp USUS|<%=Forum_info(7)&Forum_TopicPic(6)%> FKUS|dvbbs5/dispbbs.asp FSUS|dvbbs5/pic/gotop.gif FAUS|dvbbs5/SaveReAnnounce.asp FHUS|dvbbs5/reg.asp FHUS|dvbbs5/lostpass.asp FHUS|dvbbs5/admin_postings.asp FHUS|dvbbs5/admin_postings.asp FHUS|dvbbs5/admin_postings.asp FHUS|dvbbs5/admin_postings.asp FHUS|dvbbs5/admin_postings.asp FHUS|dvbbs5/admin_postings.asp FHUS|dvbbs5/admin_postings.asp FHUS|dvbbs5/announcements.asp FAUS|dvbbs5/preview.asp
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_backlinkinfo:VX|dvbbs5/queryresult.asp dvbbs5/saveannounce.asp dvbbs5/savereannounce.asp dvbbs5/index.asp dvbbs5/saveditannounce.asp dvbbs5/savevote.asp dvbbs5/dispbbs.asp
