vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|09 Oct 2002 08:59:12 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|09 Oct 2002 08:59:12 -0000
vti_filesize:IR|29479
vti_cachedlinkinfo:VX|S|<%=htmlencode(rs("face"))%> S|<%=Forum_info(7)%>zhuangtai.gif H|javascript:openScript('messanger.asp?action=new&touser=<%=htmlencode(username)%>',500,400) H|friendlist.asp H|queryResult.asp H|admin_lockuser.asp H|admin_lockuser.asp H|admin_lockuser.asp H|admin_lockuser.asp H|admin_lockuser.asp A|admin_lockuser.asp H|look_ip.asp
vti_cachedsvcrellinks:VX|USUS|<%=htmlencode(rs("face"))%> USUS|<%=Forum_info(7)%>zhuangtai.gif SHUS|javascript:openScript('messanger.asp?action=new&touser=<%=htmlencode(username)%>',500,400) FHUS|dvbbs5/friendlist.asp FHUS|dvbbs5/queryResult.asp FHUS|dvbbs5/admin_lockuser.asp FHUS|dvbbs5/admin_lockuser.asp FHUS|dvbbs5/admin_lockuser.asp FHUS|dvbbs5/admin_lockuser.asp FHUS|dvbbs5/admin_lockuser.asp FAUS|dvbbs5/admin_lockuser.asp FHUS|dvbbs5/look_ip.asp
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_backlinkinfo:VX|dvbbs5/announcements.asp dvbbs5/queryresult.asp dvbbs5/viewpaper.asp dvbbs5/friendlist.asp dvbbs5/toplist.asp dvbbs5/viewrecycle.asp dvbbs5/admin_user.asp dvbbs5/index.asp dvbbs5/usersms.asp dvbbs5/viewvoters.asp
