vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|15 Oct 2002 03:24:30 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|15 Oct 2002 03:24:30 -0000
vti_filesize:IR|18006
vti_cachedlinkinfo:VX|S|js/fader.js H|boardhelp.asp H|reg.asp H|login.asp H|JavaScript:openScript('messanger.asp?action=new',500,400) H|topicwithme.asp H|topicwithme.asp H|dispuser.asp S|pic/mail.wav S|<%=Forum_info(7)%>msg_new_bar.gif H|usersms.asp H|javascript:openScript('messanger.asp?action=read&id=<%=inceptid(1)%>&sender=<%=inceptid(2)%>',500,400) S|<%=Forum_info(7)%>msg_no_new_bar.gif H|usersms.asp H|dispuser.asp H|toplist.asp H|queryresult.asp H|toplist.asp H|toplist.asp A|login.asp H|reg.asp H|lostpass.asp H|list.asp A|login.asp H|reg.asp H|lostpass.asp S|<%=Forum_info(7)&Forum_statePic(6)%> H|list.asp H|dispuser.asp H|dispbbs.asp S|<%=Forum_info(7)%>lastpost.gif H|dispbbs.asp H|boardstat.asp S|<%=Forum_info(7)&Forum_pic(0)%> S|<%=Forum_info(7)&Forum_pic(1)%> S|<%=Forum_info(7)&Forum_pic(2)%> S|<%=Forum_info(7)&Forum_pic(3)%> S|<%=Forum_info(7)&Forum_pic(4)%> S|<%=Forum_info(7)&Forum_pic(6)%> S|<%=Forum_info(7)&Forum_pic(7)%> S|<%=Forum_info(7)&Forum_pic(14)%>
vti_cachedsvcrellinks:VX|FSUS|dvbbs5/js/fader.js FHUS|dvbbs5/boardhelp.asp FHUS|dvbbs5/reg.asp FHUS|dvbbs5/login.asp SHUS|JavaScript:openScript('messanger.asp?action=new',500,400) FHUS|dvbbs5/topicwithme.asp FHUS|dvbbs5/topicwithme.asp FHUS|dvbbs5/dispuser.asp FSUS|dvbbs5/pic/mail.wav USUS|<%=Forum_info(7)%>msg_new_bar.gif FHUS|dvbbs5/usersms.asp SHUS|javascript:openScript('messanger.asp?action=read&id=<%=inceptid(1)%>&sender=<%=inceptid(2)%>',500,400) USUS|<%=Forum_info(7)%>msg_no_new_bar.gif FHUS|dvbbs5/usersms.asp FHUS|dvbbs5/dispuser.asp FHUS|dvbbs5/toplist.asp FHUS|dvbbs5/queryresult.asp FHUS|dvbbs5/toplist.asp FHUS|dvbbs5/toplist.asp FAUS|dvbbs5/login.asp FHUS|dvbbs5/reg.asp FHUS|dvbbs5/lostpass.asp FHUS|dvbbs5/list.asp FAUS|dvbbs5/login.asp FHUS|dvbbs5/reg.asp FHUS|dvbbs5/lostpass.asp USUS|<%=Forum_info(7)&Forum_statePic(6)%> FHUS|dvbbs5/list.asp FHUS|dvbbs5/dispuser.asp FHUS|dvbbs5/dispbbs.asp USUS|<%=Forum_info(7)%>lastpost.gif FHUS|dvbbs5/dispbbs.asp FHUS|dvbbs5/boardstat.asp USUS|<%=Forum_info(7)&Forum_pic(0)%> USUS|<%=Forum_info(7)&Forum_pic(1)%> USUS|<%=Forum_info(7)&Forum_pic(2)%> USUS|<%=Forum_info(7)&Forum_pic(3)%> USUS|<%=Forum_info(7)&Forum_pic(4)%> USUS|<%=Forum_info(7)&Forum_pic(6)%> USUS|<%=Forum_info(7)&Forum_pic(7)%> USUS|<%=Forum_info(7)&Forum_pic(14)%>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
