vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|27 Sep 2002 04:10:54 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|27 Sep 2002 04:10:54 -0000
vti_filesize:IR|4393
vti_cachedlinkinfo:VX|A|login.asp H|reg.asp H|lostpass.asp H|<%=comeurl%> H|index.asp
vti_cachedsvcrellinks:VX|FAUS|dvbbs5/login.asp FHUS|dvbbs5/reg.asp FHUS|dvbbs5/lostpass.asp UHUS|<%=comeurl%> FHUS|dvbbs5/index.asp
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=REFRESH 2;\\ URL=<%=comeurl%>
