vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|14 Oct 2002 09:44:56 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|14 Oct 2002 09:44:56 -0000
vti_filesize:IR|22823
vti_cachedlinkinfo:VX|A|mymodify.asp H|allface.asp S|<%=rs("face")%> S|reg_upload.asp
vti_cachedsvcrellinks:VX|FAUS|dvbbs5/mymodify.asp FHUS|dvbbs5/allface.asp USUS|<%=rs("face")%> FSUS|dvbbs5/reg_upload.asp
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
