vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|25 Mar 2001 19:00:10 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|25 Mar 2001 19:00:10 -0000
vti_filesize:IR|3395
vti_cachedlinkinfo:VX|S|/image/bg.gif A|index.asp
vti_cachedsvcrellinks:VX|NSUS|image/bg.gif FAUS|100asp/75/index.asp
vti_cachedtitle:SR|实例　搜索引擎
vti_title:SR|实例　搜索引擎
vti_cachedbodystyle:SR|<body background="/image/bg.gif">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
