<head><title>用户注册表：</title></head>
<body bgcolor=papayawhip>
<div align="center">
  <center>
  <table border="0" cellpadding="4" cellspacing="4" width="449" height="201">
  <form action="addnewuser.asp">
  <TBODY>
    <tr>
      <td width="431" colspan="2">
        <p align="center"><b><u>用户注册表</u></b></p>
       </td>
    </tr>
    <tr>
      <td width="85">您的昵称:</td>
      <td width="332"><input class="forms" name="NAME" size="33"></td>
    </tr>
    <tr>
      <td width="85">您的密码:</td>
      <td width="332"><input class="forms" name="password" size="33" type="password" ></td>
    </tr>
    <tr>
      <td width="85">
确认密码:</td>
      <td width="332"><input class="forms" name="t_password" size="33" type="password" ></td>
    </tr>
    <tr>
      <td width="85">电子邮件:</td>
      <td width="332"><input class="forms" name="EMAIL" size="33"></td>
    </tr>
    <tr>
      <td width ="431" colspan="2"><span class="info">*以上栏目必须填写</span></td>
    </tr>
    <tr>
      <td colspan="2" width="431">
自我介绍:</td>
    </tr>
    <tr>
      <td colspan="2" width="431"><TEXTAREA class=forms cols=45 name=person rows=6></TEXTAREA></td>
    </tr>
    <tr>
      <td colspan="2" width="431">
        <p align="center"><input class="forms" name="BS" type="submit" value="提交"> <input class="forms" name="BR" type="reset" value="还原"></p></td> 
    </tr> 
</form></TBODY>
    <tr><td colspan="2" width="431">
    <P>请您注意：<BR> 1、只有在此处注册的用户中发言 
    <BR>2、尊重网上道德，遵守中华人民共和国的各项有关法律法规  
	<BR>3、承担一切因您的行为而直接或间接导致的民事或刑事法律  
	<BR>4、本站管理人员有权保留或删除其管辖留言中的任意内容  
	<BR>5、您在留言板发表的作品，本网站有权在网站内转载可引用  
	<BR>6、参与本留言表明您已经阅读并接受上述条款</P></td></tr> 
  </table>  
  </center>  
</div>  
</body>