vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|26 Mar 2001 08:09:04 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|26 Mar 2001 08:09:04 -0000
vti_filesize:IR|1880
vti_cachedlinkinfo:VX|H|display.asp A|savadata.asp
vti_cachedsvcrellinks:VX|FHUS|100asp/79/display.asp FAUS|100asp/79/savadata.asp
vti_cachedtitle:SR|留言本
vti_title:SR|留言本
vti_cachedbodystyle:SR|<body bgcolor="#e2f3f2" text="#333333">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=gb2312
