<HTML>
<HEAD>
<title>同学录</title>
</HEAD>
<BODY>
<P align=center><FONT face=隶书 size=6>实例&nbsp; 同学录</FONT></P>
<table align=center><tr><td>
<FORM action="addnews.asp" method=post id=form1 name=form1><FONT face=华文彩云 size=4>姓名：</FONT>

</td><td><FONT face=华文彩云 size=4><INPUT name=text1></FONT></td></tr>
  <TR><td><FONT face=华文彩云 size=4>性别：</FONT>
</td><td>
	<SELECT name=sel1>
	<OPTION selected>男</OPTION>
	<OPTION>女</OPTION></SELECT></td></TR>
  <TR><td><FONT face=华文彩云 size=4>生日：</FONT>
</td><td><FONT face=华文彩云 size=4><INPUT name=text2></FONT></td></TR>
  <TR><td><FONT face=华文彩云 size=4>联系电话：</FONT>
</td><td><FONT face=华文彩云 size=4><INPUT name=text3></FONT></td></TR>
  <TR><td><FONT face=华文彩云 size=4>传呼：</FONT>
</td><td><FONT face=华文彩云 size=4><INPUT name=text4></FONT></td></TR>
  <TR><td><FONT face=华文彩云 size=4>手机：</FONT>
</td><td><FONT face=华文彩云 size=4><INPUT name=text5></FONT></td></TR>
  <TR><td><FONT face=华文彩云 size=4>家庭住址：</FONT>
</td><td><FONT face=华文彩云 size=4><INPUT name=text6></FONT></td></TR>
  <TR><td><FONT face=华文彩云 size=4>所在公司：</FONT>
</td><td><FONT face=华文彩云 size=4><INPUT name=text7></FONT></td></TR>
  <TR><td><FONT face=华文彩云 size=4>电子信箱：</FONT>
</td><td><FONT face=华文彩云 size=4><INPUT name=text8></FONT></td></TR>
  <TR><td colspan=2 align=center><FONT face=华文彩云 size=4>
<INPUT type="submit" value="提 交" id=submit1 name=submit1> 
      </FONT></FORM></td></TR></table>
</BODY></HTML>
