vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|30 Mar 2001 23:17:02 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|30 Mar 2001 23:17:02 -0000
vti_filesize:IR|1474
vti_cachedlinkinfo:VX|D|register.asp D|login.asp A|message.asp
vti_cachedsvcrellinks:VX|FDUS|100asp/86/register.asp FDUS|100asp/86/login.asp FAUS|100asp/86/message.asp
vti_cachedtitle:SR|网上购物
vti_title:SR|网上购物
vti_cachedbodystyle:SR|<body bgcolor=lightgreen>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
