vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|31 Mar 2001 15:01:46 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|31 Mar 2001 15:01:46 -0000
vti_filesize:IR|2647
vti_cachedlinkinfo:VX|A|adduser.asp
vti_cachedsvcrellinks:VX|FAUS|100asp/86/adduser.asp
vti_cachedtitle:SR|网上购物
vti_title:SR|网上购物
vti_cachedbodystyle:SR|<body bgcolor=lightgreen>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
