vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|06 May 2001 03:07:10 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|06 May 2001 03:07:10 -0000
vti_filesize:IR|461
vti_cachedlinkinfo:VX|H|\\ <%=NextLink.GetNthURL("nextlink.txt",\\ I)\\ \\ %>\\ \\ 
vti_cachedsvcrellinks:VX|UHUS|\\ <%=NextLink.GetNthURL("nextlink.txt",\\ I)\\ \\ %>\\ \\ 
vti_cachedtitle:SR|ASP导航器
vti_title:SR|ASP导航器
vti_cachedbodystyle:SR|<body>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
