<html>

<head>
<title>读书室</title>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
</head>
<frameset framespacing="0" border="false" frameborder="0" scrolling="no" rows="35,*">
  <frame src="top.asp"  noresize frameborder="NO" marginwidth="0"  marginheight="0" target="_self" scrolling="no">
  <frameset cols="20%,80%">
    <frame name="menu" src="left.asp" marginwidth="10" marginheight="10" scrolling="auto" frameborder="no">
    <frame name="main" src="right.asp" marginwidth="10" marginheight="10" scrolling="auto" frameborder="no">
</frameset>
  <noframes>
  </noframes>
</frameset>

<frameset>
</frameset>
</html>