vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|28 Mar 2001 15:56:54 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|28 Mar 2001 15:56:54 -0000
vti_filesize:IR|2424
vti_cachedlinkinfo:VX|S|hand.gif A|savemessage.asp H|user_register.asp
vti_cachedsvcrellinks:VX|FSUS|100asp/80/hand.gif FAUS|100asp/80/savemessage.asp FHUS|100asp/80/user_register.asp
vti_cachedtitle:SR|网友评论：
vti_title:SR|网友评论：
vti_cachedbodystyle:SR|<body bgcolor="#f0ffff">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
