vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|21 Mar 2001 19:06:08 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|21 Mar 2001 19:06:08 -0000
vti_filesize:IR|1901
vti_cachedlinkinfo:VX|A|addnewuser.asp
vti_cachedsvcrellinks:VX|FAUS|100asp/80/addnewuser.asp
vti_cachedtitle:SR|用户注册表：
vti_title:SR|用户注册表：
vti_cachedbodystyle:SR|<body bgcolor=papayawhip>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
