vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|11 Apr 2001 21:07:02 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|11 Apr 2001 21:07:02 -0000
vti_filesize:IR|1558
vti_cachedlinkinfo:VX|A|addnews.asp
vti_cachedsvcrellinks:VX|FAUS|100asp/77/addnews.asp
vti_cachedtitle:SR|同学录
vti_title:SR|同学录
vti_cachedbodystyle:SR|<BODY>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
