vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|11 Apr 2001 20:49:00 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|11 Apr 2001 20:49:00 -0000
vti_filesize:IR|1350
vti_cachedlinkinfo:VX|D|delnews.asp H|index.asp H|add.asp H|modify.asp H|javascript:confirmDel(<%=\\ rs("id")\\ %>)
vti_cachedsvcrellinks:VX|FDUS|100asp/77/delnews.asp FHUS|100asp/77/index.asp FHUS|100asp/77/add.asp FHUS|100asp/77/modify.asp SHUS|javascript:confirmDel(<%=\\ rs("id")\\ %>)
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
