vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|11 Apr 2001 21:41:28 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|11 Apr 2001 21:41:28 -0000
vti_filesize:IR|1447
vti_cachedlinkinfo:VX|S|background.gif H|add.asp H|del.asp H|modify.asp
vti_cachedsvcrellinks:VX|FSUS|100asp/77/background.gif FHUS|100asp/77/add.asp FHUS|100asp/77/del.asp FHUS|100asp/77/modify.asp
vti_cachedtitle:SR|同学录
vti_title:SR|同学录
vti_cachedbodystyle:SR|<BODY background=background.gif>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
