vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|11 Apr 2001 21:03:40 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|11 Apr 2001 21:03:40 -0000
vti_filesize:IR|1301
vti_cachedlinkinfo:VX|D|modifydisplay.asp H|index.asp H|add.asp H|del.asp H|javascript:confirmDel(<%=\\ rs("id")\\ %>)
vti_cachedsvcrellinks:VX|FDUS|100asp/77/modifydisplay.asp FHUS|100asp/77/index.asp FHUS|100asp/77/add.asp FHUS|100asp/77/del.asp SHUS|javascript:confirmDel(<%=\\ rs("id")\\ %>)
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
