vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|02 May 2001 15:01:18 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|02 May 2001 15:01:18 -0000
vti_filesize:IR|512
vti_cachedlinkinfo:VX|
vti_cachedsvcrellinks:VX|
vti_cachedtitle:SR|满天星
vti_title:SR|满天星
vti_cachedbodystyle:SR|<Body bgcolor=#000000>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
