vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|06 May 2001 12:14:04 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|06 May 2001 12:14:04 -0000
vti_filesize:IR|591
vti_cachedlinkinfo:VX|
vti_cachedsvcrellinks:VX|
vti_cachedtitle:SR|注册表访问组件
vti_title:SR|注册表访问组件
vti_cachedbodystyle:SR|<BODY>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|GENERATOR Microsoft\\ Visual\\ Studio\\ 6.0
vti_generator:SR|Microsoft Visual Studio 6.0
