<!--#include file="CSS.ASP"-->
<html>
<head>
<title>添加成功</title>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<meta http-equiv="refresh" content="1;url=ADDDOCUMENTS.ASP"
</head>
<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0">
<table width="100%" height="100%" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td align="center">添加成功，1 秒钟后自动刷新
      <br>
      <br>
    </td>
  </tr>
</table>
</body>
</html>
