<head>
<title>功能菜单</title>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<link rel="stylesheet" href="../inc/southdns.css" type="text/css">
</head>
<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<table width="100%" border="0" cellspacing="1" cellpadding="6" bgcolor="#000000">
  <tr bgcolor="#FFCC33"> 
    <td align="center" bgcolor="#FFFF99"><b>控制面板</b></td>
  </tr>
  <tr bgcolor="#FFCC33"> 
    <td><b>用户与定单管理部分</b></td>
  </tr>
  <tr bgcolor="#FFFF99"> 
    <td bordercolor="#000000"><b>用户管理</b></td>
  </tr>
  <tr> 
    <td bordercolor="#000000" bgcolor="#FFFFCC"><a href="userselect.asp" target="mainFrame">条件查看用户资料</a></td>
  </tr>
  <tr> 
    <td bordercolor="#000000" bgcolor="#FFFFCC"><a href="viewuser.asp" target="mainFrame">批量查看用户资料</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="searchuser.asp" target="mainFrame">查询/<font color="red">编辑</font>/修改帐号</a></td>
  </tr>
  <tr bgcolor="#FFFF99"> 
    <td bordercolor="#000000"><b>订单管理</b></td>
  </tr>
  <tr> 
    <td bordercolor="#000000" bgcolor="#FFFFCC"><a href="orderselect.asp" target="mainFrame">条件查看所有订单</a></td>
  </tr>
  <tr> 
    <td bordercolor="#000000" bgcolor="#FFFFCC"><a href="userorderlog.asp" target="mainFrame">批量查看所有订单</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="searchorders.asp" target="mainFrame">根据订单号查询</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000" height="26"><a href="viewusererror.asp" target="mainFrame">查看用户投诉</a></td>
  </tr>
  <tr bgcolor="#FFCC33"> 
    <td><b>商品管理部分</b></td>
  </tr>
  <tr bgcolor="#FFFF99"> 
    <td bordercolor="#000000"><b>类别管理</b></td>
  </tr>
  <tr> 
    <td bordercolor="#000000" bgcolor="#FFFFCC"><a href="area.asp" target="mainFrame">分类相关</a></td>
  </tr>
  <tr> 
    <td bordercolor="#000000" bgcolor="#FFFFCC"><a href="gys.asp" target="mainFrame">供应商管理</a></td>
  </tr>
  <tr bgcolor="#FFFF99"> 
    <td bordercolor="#000000"><b>商品管理</b></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="viewsubs.asp" target="mainFrame">条件查看所有商品</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="subs.asp" target="mainFrame">批量查看所有商品</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="addsubs-web.asp" target="mainFrame"><font color="#FF0000">添加网站建设</font></a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="addsubs-step1.asp" target="mainFrame"><font color="#FF0000">添加商品</font></a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="searchsubs.asp" target="mainFrame">查看/修改/删除商品</a></td>
  </tr>
  <tr> 
    <td bgcolor="#FFCC33"><b>其他管理部分</b></td>
  </tr>
  <tr bgcolor="#FFFF99"> 
    <td bordercolor="#000000"><b>邮件管理</b></td>
  </tr>
  <tr> 
    <td bordercolor="#000000" bgcolor="#FFFFCC"><a href="sendmail.asp" target="mainFrame">发送邮件</a></td>
  </tr>
  <tr bgcolor="#FFFF99"> 
    <td bordercolor="#000000"><b>公告/折扣 及其他</b></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="sample_site_add.asp" target="mainFrame">添加 -- 样板网站</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="sample_site_view.asp" target="mainFrame">浏览/删除 -- 样板网站</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="sample_area_add.asp" target="mainFrame">添加 -- 样板空间</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="sample_area_view.asp" target="mainFrame">浏览/删除 -- 样板空间</a></td>
  </tr>

  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="adddeleddomain.asp" target="mainFrame">添加DELEDDOMAIN</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="viewdeleddomain.asp" target="mainFrame">浏览/删除DELEDDOMAIN</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="addfaq.asp" target="mainFrame">添加FAQ/BASE</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="viewfaq.asp" target="mainFrame">浏览/删除FAQ/BASE</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="adddocuments.asp" target="mainFrame">添加文档</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="viewdocuments.asp" target="mainFrame">浏览/删除文档</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="addnews.asp" target="mainFrame">添加公告</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="viewnews.asp" target="mainFrame">浏览/删除公告</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="bill.asp" target="mainFrame">设置站内广告</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="akehu.asp" target="mainFrame">添加成交客户</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="discount.asp" target="mainFrame">代理人享受折扣</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="addpayment.asp" target="mainFrame">添加支付方式</a></td>
  </tr>
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="viewpayment.asp" target="mainFrame">浏览和删除支付方式</a></td>
  </tr>
  <%if session("y_eshop_aleave")="s" then%> 
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="addadmin.asp" target="mainFrame">添加一个管理员</a></td>
  </tr>
  <%end if%> 
  <tr bgcolor="#FFFFCC"> 
    <td bordercolor="#000000"><a href="adminlogin.asp?logout=ture" target="mainFrame">登出</a></td>
  </tr>
  <tr> 
    <td bordercolor="#000000" bgcolor="#FFFF99"><b>版权所有</b></td>
  </tr>
</table>
</body>
</html>
