vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|28 Mar 2001 14:56:56 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|28 Mar 2001 14:56:56 -0000
vti_filesize:IR|2105
vti_cachedlinkinfo:VX|D|add.asp H|display.asp S|picture\\\\sohu.gif S|picture\\\\51job.JPG S|picture\\\\sina.gif S|picture\\\\chinahr.gif S|picture\\\\263.gif S|picture\\\\chinaren.gif S|picture\\\\china.gif S|picture\\\\yahoo.JPG A|add.asp
vti_cachedsvcrellinks:VX|FDUS|100asp/82/add.asp FHUS|100asp/82/display.asp NSUS|/100asp/82/picture\\\\sohu.gif NSUS|/100asp/82/picture\\\\51job.JPG NSUS|/100asp/82/picture\\\\sina.gif NSUS|/100asp/82/picture\\\\chinahr.gif NSUS|/100asp/82/picture\\\\263.gif NSUS|/100asp/82/picture\\\\chinaren.gif NSUS|/100asp/82/picture\\\\china.gif NSUS|/100asp/82/picture\\\\yahoo.JPG FAUS|100asp/82/add.asp
vti_cachedtitle:SR|计数器
vti_title:SR|计数器
vti_cachedbodystyle:SR|<BODY>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
