vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|28 Mar 2001 13:42:44 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|28 Mar 2001 13:42:44 -0000
vti_filesize:IR|2414
vti_cachedlinkinfo:VX|D|index.asp S|picture/Map.jpg K|INDEX.ASP S|picture/<%=rs("todayday")%>.gif S|picture/<%=rs("tomorrowtday")%>.gif
vti_cachedsvcrellinks:VX|FDUS|100asp/83/index.asp FSUS|100asp/83/picture/Map.jpg FKUS|100asp/83/INDEX.ASP USUS|picture/<%=rs("todayday")%>.gif USUS|picture/<%=rs("tomorrowtday")%>.gif
vti_cachedtitle:SR|实例　天气预报
vti_title:SR|实例　天气预报
vti_cachedbodystyle:SR|<body>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
