vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|07 Jun 2000 12:35:06 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|07 Jun 2000 12:35:06 -0000
vti_filesize:IR|1304
vti_cachedlinkinfo:VX|H|register.htm H|login.htm H|visitor.htm H|help.htm H|leavemessage.htm
vti_cachedsvcrellinks:VX|FHUS|100asp/91-100/register.htm FHUS|100asp/91-100/login.htm FHUS|100asp/91-100/visitor.htm NHUS|100asp/91-100/help.htm FHUS|100asp/91-100/leavemessage.htm
vti_cachedbodystyle:SR|<body bgcolor=#c1f7d8>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
