vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|27 Mar 2001 15:10:16 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|27 Mar 2001 15:10:16 -0000
vti_filesize:IR|535
vti_cachedlinkinfo:VX|F|top.asp F|top.asp F|bottom.htm
vti_cachedsvcrellinks:VX|FFUS|100asp/91-100/top.asp FFUS|100asp/91-100/top.asp NFUS|100asp/91-100/bottom.htm
vti_cachedtitle:SR|
vti_title:SR|
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_hasframeset:BR|true
