vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|31 Mar 2001 12:19:06 -0000
vti_extenderversion:SR|4.0.2.4022
vti_cacheddtm:TX|31 Mar 2001 12:19:06 -0000
vti_filesize:IR|811
vti_cachedlinkinfo:VX|H|changepassword.htm H|readmessage.asp H|showlist.asp H|publisharticle.htm H|http://fang/bbs/
vti_cachedsvcrellinks:VX|FHUS|100asp/91-100/changepassword.htm FHUS|100asp/91-100/readmessage.asp FHUS|100asp/91-100/showlist.asp FHUS|100asp/91-100/publisharticle.htm NHHS|http://fang/bbs/
vti_cachedbodystyle:SR|<BODY bgcolor=#c1f7d8>
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|GENERATOR Microsoft\\ Visual\\ Studio\\ 6.0
vti_generator:SR|Microsoft Visual Studio 6.0
